version: "3.8"
services:
  trackmania:
    image: evotm/trackmania
    ports:
      - 2351:2350/udp
      - 2351:2350/tcp
      - "127.0.0.1:5001:5000/tcp" # Be careful opening XMLRPC! Only if you really need to.
    environment:
      MASTER_LOGIN: "SERVERLOGIN"
      MASTER_PASSWORD: "SERVERPASS"
      XMLRPC_ALLOWREMOTE: "True"
    volumes:
      - UserData:/server/UserData
  db:
    image: postgres
    restart: always
    ports:
      - "127.0.0.1:5438:5432"
    volumes:
      - POSTGRESData:/var/lib/postgresql/data 
    environment:
      - POSTGRES_USER=evosc
      - POSTGRES_PASSWORD=evosc123!
      - POSTGRES_DB=evosc
  adminer:
    image: adminer
    restart: always
    ports:
      - "127.0.0.1:8081:8080"
volumes:
  UserData: null
  POSTGRESData: null
