version: "3.8"
services:
  trackmania:
    image: evotm/trackmania
    ports:
      - 2350:2350/udp
      - 2350:2350/tcp
      - "5001:5000/tcp" # Be careful opening XMLRPC! Only if you really need to.
    environment:
      MASTER_LOGIN: "CHANGEME :)" # Create server credentials at https://players.trackmania.com
      MASTER_PASSWORD: "CHANGEME :)" # Create server credentials at https://players.trackmania.com
      XMLRPC_ALLOWREMOTE: "True"
    volumes:
      - UserData:/server/UserData
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - PostgresData:/var/lib/postgresql/data 
    environment:
      - POSTGRES_PASSWORD=evosc
      #- POSTGRES_USER=CHANGEME :) for a production server please change those values!
      #- POSTGRES_DB=CHANGEME :)
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    extra_hosts: 
        - "host.docker.internal:host-gateway"
    environment:
      PGADMIN_DEFAULT_EMAIL: PLEASE@CHANGE.ME
      PGADMIN_DEFAULT_PASSWORD: CHANGEME
    ports:
      - "8081:80"
volumes:
  UserData: null
  PostgresData: null
