version: "3.8"
services:
  trackmania:
    image: evotm/trackmania
    ports:
      - 2350:2350/udp
      - 2350:2350/tcp
      - "127.0.0.1:5001:5000/tcp" # Be careful opening XMLRPC! Only if you really need to.
    environment:
      MASTER_LOGIN: "evoserv"
      MASTER_PASSWORD: "FY@qh+G!}g9{*f&w"
      XMLRPC_ALLOWREMOTE: "True"
    volumes:
      - UserData:/server/UserData
  db:
    image: postgres
    restart: always
    ports:
      - "127.0.0.1:5438:5432"
    volumes:
      - POSTGRESData:/var/lib/postgresql/data 
    environment:
      - POSTGRES_USER=evosc
      - POSTGRES_PASSWORD=evosc123!
      - POSTGRES_DB=evosc
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: PLEASE@CHANGE.ME
      PGADMIN_DEFAULT_PASSWORD: CHANGEME
    ports:
      - "8081:80"
volumes:
  UserData: null
  POSTGRESData: null
