[info]
# A unique name for this module, this is used as a identifier
name = "ASayModule"
# The title of the module
title = "ASay Module"
# A short description of what the module is and does
summary = "A module for displaying an announcement message to all players in a prominent position on the screen."
# The current version of this module, using SEMVER
version = "1.0.0"
# The name of the author that created this module
author = "Evo"
