[info]
# A unique name for this module, this is used as a identifier
name = "TeamChatModule"
# The title of the module
title = "Team Chat"
# A short description of what the module is and does
summary = "Functionality for teams to only send messages to themselves."
# The current version of this module, using SEMVER
version = "1.0.0"
# The name of the author that created this module
author = "Evo"
