[info]
# A unique name for this module, this is used as a identifier
name = "GameModeUiModule"
# The title of the module
title = "GameMode UI"
# A short description of what the module is and does
summary = "Change appearance of UI modules provided by the gamemodes."
# The current version of this module, using SEMVER
version = "1.0.0"
# The name of the author that created this module
author = "Evo"
