<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>EvoSC.Modules.Official.ContractApiConsumerModule</RootNamespace>
        <EvoSCModulesOutDir>$(MSBuildThisFileDirectory)..\..\..\tests\EvoSC.Modules.Tests\bin\$(Configuration)\$(TargetFramework)\modules\ContractApiConsumerModule</EvoSCModulesOutDir>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\EvoSC.Modules.SourceGeneration\EvoSC.Modules.SourceGeneration.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
        <ProjectReference Include="..\..\EvoSC.Modules\EvoSC.Modules.csproj" />
        <ProjectReference Include="..\..\EvoSC.Modules.Build\EvoSC.Modules.Build.csproj" ReferenceOutputAssembly="false" />
        <ProjectReference Include="..\ContractApiProviderModule\ContractApiProviderModule.csproj" ReferenceOutputAssembly="false" EvoSCModule="true" />
    </ItemGroup>

    <Import Project="..\..\EvoSC.Modules.Build\build\EvoSC.Modules.Build.targets" />

</Project>