services:
  trackmania:
    image: evoesports/trackmania
    restart: always
    ports:
      - "2350:2350/udp"
      - "2350:2350/tcp"
      - "5001:5000"
    environment:
      - MASTER_LOGIN=
      - MASTER_PASSWORD=
      - XMLRPC_ALLOWREMOTE=True
    volumes:
      - UserData:/server/UserData
    
  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_PASSWORD=evosc_sharp
      - POSTGRES_USER=evosc_sharp
      - POSTGRES_DB=evosc_sharp
    ports:
      - "5432:5432"

volumes:
  PostgresData: null
  UserData: null
