[dedicated]
    host = "127.0.0.1"
    port = 5001
    login = "SuperAdmin"
    password = "SuperAdmin"

[database]
    type = "mysql"
    host = "localhost"
    port = 3306
    dbname = "evosc"
    user = "evosc"
    password = "evosc123!"
    
[theme]
    default = "$fff"
    info =  "$29b"
    highlight = "$eee"
    success = "$5b6"
    warning = "$e83"
    danger = "$c44"