[info]
# A unique name for this module, this is used as an identifier
name = "LiveRankingModule"
# The title of the module
title = "LiveRanking Module"
# A short description of what the module is and does
summary = "Shows a widget with the best scores of the running match."
# The current version of this module, using SEMVER
version = "2.0.0"
# The name of the author that created this module
author = "Evo"
