[info]
name = "SpectatorCamModeModule"
title = "Spectator Cam Mode"
summary = "Shows and allows changing the cam mode."
version = "1.0.0"
author = "Evo"

[dependencies]
SpectatorTargetInfoModule = "1.0.0"
GameModeUiModule = "1.0.0"
