//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EvoSC.Modules.Official.PlayerRecords {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EvoSC.Modules.Official.PlayerRecords.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $&lt;{0}$&gt; got a new pb with time {1}..
        /// </summary>
        internal static string PlayerGotANewPb {
            get {
                return ResourceManager.GetString("PlayerGotANewPb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You got a new pb with time {0}.
        /// </summary>
        internal static string YouGotANewPb {
            get {
                return ResourceManager.GetString("YouGotANewPb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have not set a time on this map yet..
        /// </summary>
        internal static string YouHaveNotSetATime {
            get {
                return ResourceManager.GetString("YouHaveNotSetATime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your current pb is $&lt;$fff{0}$&gt;.
        /// </summary>
        internal static string YourCurrentPbIs {
            get {
                return ResourceManager.GetString("YourCurrentPbIs", resourceCulture);
            }
        }
    }
}
