//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EvoSC.Modules.Official.SetName {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EvoSC.Modules.Official.SetName.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Did not change the name as it equals the old..
        /// </summary>
        internal static string DidNotChangeName {
            get {
                return ResourceManager.GetString("DidNotChangeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit your nickname.
        /// </summary>
        internal static string EditYourNickname {
            get {
                return ResourceManager.GetString("EditYourNickname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name successfully set!.
        /// </summary>
        internal static string NameSuccessfullySet {
            get {
                return ResourceManager.GetString("NameSuccessfullySet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $f00Cancel.
        /// </summary>
        internal static string UI_Cancel {
            get {
                return ResourceManager.GetString("UI.Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nickname:.
        /// </summary>
        internal static string UI_Nickname {
            get {
                return ResourceManager.GetString("UI.Nickname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} changed their name to {1}.
        /// </summary>
        internal static string UI_PlayerChangedTheirName {
            get {
                return ResourceManager.GetString("UI.PlayerChangedTheirName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        internal static string UI_Submit {
            get {
                return ResourceManager.GetString("UI.Submit", resourceCulture);
            }
        }
    }
}
